version: "4.0"


services:
  postgres:
    image: postgres:${POSTGRES_VERSION}
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      # - postgres-db-volume:/var/lib/postgresql/data
      - ./pg_data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    networks:
      - ${CLUSTER_NAME}
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "airflow" ]
      interval: 5s
      retries: 5
    restart: always

  hadoop:
    hostname: ${CLUSTER_NAME}
    image: ${CLUSTER_NAME}:${HADOOP_VERSION}
    container_name: hadoop
    build:
      context: .
      dockerfile: ./${CLUSTER_NAME}/Dockerfile
      args:
        HADOOP_VERSION: ${HADOOP_VERSION}
        HIVE_VERSION: ${HIVE_VERSION}
    depends_on:
      - postgres
    ports:
      # HDFS
      - 50070:50070
      - 50090:50090
      - 50075:50075
      - 8020:8020
      # Hive
      - 10000:10000
    volumes:
      - hadoop:/opt/hadoop
      - hive:/opt/hive
      - spark:/opt/spark
    networks:
      - ${NETWORK_NAME}

volumes:
  hadoop:
    name: hadoop
  hive:
    name: hive
  spark:
    name: spark


networks:
  ${NETWORK_NAME}:
    name: ${NETWORK_NAME}
